config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new, :show]

  resources :programs, only: [:index, :show]
  get '/popular_programs', to: 'programs#search_popular_programs'

  resources :subscriptions, only: [:create, :new, :destroy]
  get '/subscriptions/user_programs/:user_id', to: 'subscriptions#user_programs'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/program.rb
class Program < ApplicationRecord
  has_many :subscriptions
  has_many :users, through: :subscriptions
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :program

  validates :user_id, uniqueness: { scope: :program_id }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :subscriptions
  has_many :programs, through: :subscriptions

  validates :name, presence: true
  validates_format_of :email, with: /\A([^\s]+)((?:[-a-z0-9]\.)[a-z]{2,})\z/i

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  def index
    @programs = Program.all
  end

  def show
    @program = Program.find(params[:id])

  rescue ActiveRecord::RecordNotFound
    render json: { error: 'Program not found' }, status: :not_found
  end

  def search_popular_programs
    term = params[:term]

    if term.blank?
      render json: { error: 'Search term cannot be blank' }, status: :unprocessable_entity
      return
    end

    @popular_programs = Program.where('title ILIKE ?', "%#{term}%")
                               .joins(:subscriptions)
                               .group('programs.id')
                               .order('COUNT(subscriptions.id) DESC')
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  # @NOTE: turn off CSRF
  skip_before_action :verify_authenticity_token

  def create
    user = User.find(params[:user_id])
    program = Program.find(params[:program_id])

    if Subscription.exists?(user: user, program: program)
      render json: { error: 'User is already subscribed to this program' }, status: :unprocessable_entity
    else
      render json: Subscription.create(
        user_id: params[:user_id],
        program_id: params[:program_id]
      )
    end
  end

  def new
  end

  def destroy
    subscription = Subscription.find(params[:id])

    if subscription.destroy
      render json: { message: 'Subscription deleted successfully' }
    else
      render json: { error: 'Failed to delete subscription' }, status: :unprocessable_entity
    end

    rescue ActiveRecord::RecordNotFound => e
      render json: { error: e.message }, status: :not_found
  end

  def user_programs
    @user_programs = Subscription.where(:user_id => params[:user_id]).includes(:user, :program)
    # render json: user_programs
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # @NOTE: turn off CSRF
  skip_before_action :verify_authenticity_token

  def index
    @users = User.all
  end

  def create
    render json: User.create(
      email: params[:email],
      name: params[:name]
    )
  end

  def show
    @user = User.find(params[:id])

    render json: @user

    rescue ActiveRecord::RecordNotFound
      render json: { error: 'User not found' }, status: :not_found
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestApiService</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/programs/index.html.erb
<h1>All programs</h1>
<%@programs.each do |program| %>
  <%=link_to program.title, "/programs/#{program.id}" %>
<% end %>

app/views/programs/search_popular_programs.html.erb
<h1>Popular Programs</h1>

<ul>
  <% @popular_programs.each do |program| %>
    <li>
      <h2><%= program.title %></h2>
      <p><%= program.description %></p>
    </li>
  <% end %>
</ul>

app/views/programs/show.html.erb
<h1>Program <%=@program.id %></h1>
<p><%=@program.title %></p>
<p><%=@program.description %></p>

app/views/subscriptions/new.html.erb
<h1>Create new subscription</h1>

<%= form_with(model: @subscriptions, url: subscriptions_path) do |form| %>
  <%= form.label :user_id %>
  <%= form.text_field :user_id %>

  <%= form.label :program_id %>
  <%= form.text_field :program_id %>

  <%= form.submit 'Create' %>
<% end %>

app/views/subscriptions/user_programs.html.erb
<h1>User programs</h1>
<%
  user_subscriptions = {}

  @user_programs.each do |subscription|
    user = subscription.user
     program = subscription.program

     if user_subscriptions.key?(user)
       user_subscriptions[user] << program.title
     else
       user_subscriptions[user] = [program.title]
     end
  end

  user_subscriptions.each do |user, programs|
%>
  <p><%="#{user.name} - #{programs.join(', ')}" %></p>
<% end %>

app/views/users/new.html.erb
<h1>Create new user</h1>

<%= form_with(model: @users, url: users_path) do |form| %>
  <%= form.label :email %>
  <%= form.text_field :email %>

  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.submit 'Create' %>
<% end %>

app/views/users/show.html.erb
<h1>User <%=@user.id %></h1>

<p>email: <%= @user.email %></p>
<p>name: <%= @user.name %></p>